apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: qr
build:
  local:
    useBuildkit: true
  artifacts:
    - image: qr-api
      context: .
      docker:
        dockerfile: api/Dockerfile
    - image: qr-engine
      context: .
      docker:
        dockerfile: engine/Dockerfile
manifests:
  rawYaml:
    - manifests/dev/api.yaml
    - manifests/dev/engine.yaml

deploy:
  kubectl: {}
