apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: qer
build:
  local:
    useBuildkit: true
  artifacts:
    - image: qer-api
      context: .
      docker:
        dockerfile: api/Dockerfile
    - image: qer-engine
      context: .
      docker:
        dockerfile: engine/Dockerfile
manifests:
  rawYaml:
    - manifests/dev/api.yaml
    - manifests/dev/engine.yaml
    - manifests/dev/postgres-pvc.yaml
    - manifests/dev/postgres.yaml

deploy:
  kubectl: {}
