[package]
name = "qer-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.4"
tonic = "0.14.6"
tonic-prost = "0.14.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic-health = "0.14.6"
thiserror = "2.0.20"
jsonwebtoken = { version = "11", features = ["aws_lc_rs"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }
redisclient = { package="redis", version = "1.7.0", features = ["tokio-comp", "r2d2"] }

[dependencies.uuid]
version = "1.25.0"
features = [
    "v4",
    "v7",
]

[build-dependencies]
tonic-prost-build = "0.14.6"

[dev-dependencies]
testcontainers-modules = { version = "0.15.0", features = ["postgres", "redis"] }
