# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.8.0/configuration-schema.json
package: openapi
output: gen/openapi/qer-api.go

generate:
  models: true
  chi-server: true
  strict-server: true
